{{- if and .Values.secrets.github.enabled (not .Values.secrets.github.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hnc.fullname" . }}-github
  labels:
    {{- include "hnc.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.secrets.github.token | b64enc }}
{{- end }}
---
{{- if and .Values.secrets.kubeconfig.enabled (not .Values.secrets.kubeconfig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hnc.fullname" . }}-kubeconfig
  labels:
    {{- include "hnc.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config: {{ .Values.secrets.kubeconfig.config | b64enc }}
{{- end }}
---
{{- if and .Values.secrets.tls.enabled (not .Values.secrets.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hnc.fullname" . }}-tls
  labels:
    {{- include "hnc.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  {{ .Values.secrets.tls.certKey }}: {{ .Values.secrets.tls.cert | b64enc }}
  {{ .Values.secrets.tls.keyKey }}: {{ .Values.secrets.tls.key | b64enc }}
{{- end }}