{{- if .Values.secrets.github.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hnc.fullname" . }}-github
  labels:
    {{- include "hnc.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.secrets.github.token | b64enc }}
{{- end }}