name: ci
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      enable_hhfab_validation:
        description: 'Enable HHFab validation'
        required: false
        default: 'false'
        type: boolean
      enable_k8s_validation:
        description: 'Enable K8s validation'
        required: false
        default: 'false'
        type: boolean
      enable_integration:
        description: 'Enable integration tests'
        required: false
        default: 'false'
        type: boolean

jobs:
  # Core CI pipeline - matrix for Node 18 & 20
  core-tests:
    name: Core Tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20']
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: TypeScript type checking
        run: npm run typecheck
        
      - name: Build application
        run: npm run build
        
      - name: Run unit tests (including property tests)
        run: npm test -- --run
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run E2E golden path test
        run: npm run e2e
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Test Storybook stories
        run: npm run test-storybook

  # Optional GitHub integration tests (only when secrets exist)
  integration-github:
    name: GitHub Integration (Node 20)
    runs-on: ubuntu-latest
    needs: core-tests
    if: ${{ secrets.GITHUB_TOKEN && vars.GIT_REMOTE }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run GitHub integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REMOTE: ${{ vars.GIT_REMOTE }}
          FEATURE_GIT: 'true'
        run: npm run int:gh
        
  # Optional K8s integration tests (only when kubeconfig exists)
  integration-k8s:
    name: K8s Integration (Node 20)
    runs-on: ubuntu-latest
    needs: core-tests
    if: ${{ secrets.KUBECONFIG || github.event.inputs.enable_k8s_validation == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
          
      - name: Configure kubectl (if kubeconfig provided)
        if: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl cluster-info
          
      - name: Setup local k8s cluster (if no kubeconfig)
        if: ${{ !secrets.KUBECONFIG }}
        uses: helm/kind-action@v1
        with:
          version: v0.20.0
          kubectl_version: v1.28.0
          cluster_name: hnc-test
          
      - name: Run K8s integration tests
        env:
          FEATURE_K8S: 'true'
        run: npm run int:k8s:ci

  # Optional HHFab validation (only when enabled)
  validation-hhfab:
    name: HHFab Validation (Node 20)
    runs-on: ubuntu-latest
    needs: core-tests
    if: ${{ vars.ENABLE_HHFAB_VALIDATION == 'true' || vars.HHFAB || github.event.inputs.enable_hhfab_validation == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run HHFab validation tests
        env:
          HHFAB: ${{ vars.HHFAB || '/usr/local/bin/hhfab' }}
        run: npm run validate:hhfab:ci

  # Optional K8s validation (dry-run only, no cluster required)
  validation-k8s:
    name: K8s Validation (Node 20)
    runs-on: ubuntu-latest
    needs: core-tests
    if: ${{ vars.ENABLE_K8S_VALIDATION == 'true' || github.event.inputs.enable_k8s_validation == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run K8s validation tests
        env:
          FEATURE_K8S: 'true'
        run: npm run validate:k8s:ci